# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - tomaszpakula-client

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_1218e9290dce4986afbc5db4c3698ef6 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_4421825957d245d6af41c50dc3c6fba1 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_1218e9290dce4986afbc5db4c3698ef6 }}/tomaszpakula/shop-client:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'tomaszpakula-client'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_3ca57d53c5414a6daad2d79cba49bacf }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_1218e9290dce4986afbc5db4c3698ef6 }}/tomaszpakula/shop-client:${{ github.sha }}'